SmartTyping/urls.py
from django.contrib import admin
from homepage import views
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),

    path('', include('homepage.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path
from homepage import views
from homepage import ajax

app_name = 'homepage'

urlpatterns = [
    # giới thiệu
    path('', views.index, name='index'),
    path('gioi-thieu', views.about, name='about'),
    path('xem-them', views.aboutbee, name="aboutbee"),

    # dang ky - dang nhap - trang ca nhan
    path('dang-ki', views.myregister, name='register'),
    path('dang-nhap',  views.mylogin, name="login"),
    path('dang-xuat', views.mylogout, name="logout"),
    path('khoi-phuc-mat-khau',  views.resetpassword, name="resetpassword"),
    path('trang-ca-nhan/<int:id>', views.dashboard, name='dashboard'),
    path('cap-nhat-thong-tin-ca-nhan', views.updateinfo, name='updateinfo'),

    # bài học
    path('danh-sach-bai-hoc', views.lesson, name='lesson'),
    path('chu-de-bai-hoc-<int:id1>/bai-hoc-<int:id2>', views.lessondetail, name='lessondetail'),
    path('chu-de-bai-hoc-<int:id1>/bai-hoc-<int:id2>/hoat-dong-<int:id3>', views.activitydetail, name='activitydetail'),
    path('ajaxtrackcompleteactivity', ajax.ajaxtrackcompleteactivity, name="ajaxtrackcompleteactivity"),

    # game luyện tập
    path('luyen-tap', views.practice, name="practice"),
    path('luyen-tap/tro-choi-<int:id>', views.practicelevel, name="practicelevel"),
    path('luyen-tap/tro-choi-<int:id1>/level-<int:id2>', views.practicedetail, name="practicedetail"),
    path('ajaxtrackcompletelevelgame', ajax.ajaxtrackcompletelevelgame, name="ajaxtrackcompletelevelgame"),

    # kiểm tra - cuộc thi
    path('kiem-tra', views.test, name="test"),
    path('kiem-tra-thoi-gian/<int:id>', views.timetestdetail, name="timetestdetail"),
    path('kiem-tra-van-ban/<int:id>', views.contenttestdetail, name="contenttestdetail"),
    path('cuoc-thi', views.competition, name="competition"),
    
    # tin tức - tài liệu
    path('tin-tuc', views.news, name='news'),
    path('tin-tuc-<int:id>', views.newsdetail, name='newsdetail'),
    path('tai-lieu', views.document, name='document'),
    path('tai-lieu-<int:id>', views.docdetail, name='docdetail'),

    # hỗ trợ
    path('ho-tro', views.support, name="support"),
    path('cau-hoi-thuong-gap', views.faq, name='faq'),
    path('lien-he', views.contact, name='contact'),
]

homepage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.contrib import messages
# from django.http import FileResponse
from homepage.models import *
from homepage.homefunction import *
import random

# introduction
def index(request):
    users = User.objects.all()
    context = {
        'users': users,
    }
    return render(request, 'homepage/index.html', context)

def about(request):
    context = {
    }
    return render(request, 'homepage/about.html', context)

def aboutbee(request):
    context = {
    }   
    return render(request, 'homepage/aboutbee.html', context)

# login - logout - dashboard
def myregister(request):
    message = ''
    # Nếu đã đăng nhập --> index
    if request.user.is_authenticated:
        return render(request, 'homepage/updateinfo.html')
    else:
        if request.method == 'POST':  
            username = request.POST.get('username')
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            avatar = request.FILES.get('avatar')

            # Kiểm tra username, password1 và password2 có rỗng hoặc password1 != password2 hay không
            if username == '' or password1 == '' or password2 == '' or password1 != password2:
                return render(request, 'homepage/register.html')
            else:
                new_user = User()
                new_user.username = username
                new_user.set_password(password1)
                new_user.save()
                user = authenticate(username=username, password=password1)
                login(request, user)

                new_account = Account()
                new_account.username = new_user
                new_account.callsignid = CallSign.objects.get(pk = 1)
                new_account.password = password1
                new_account.experience = 0
                # new_account.avatar = tokenFile(avatar, username)
                new_account.avatar = tokenFile(avatar,'media/users', username ,1)

                new_account.save()
                # return render(request, 'homepage/updateinfo.html')
                return redirect('homepage:updateinfo')
        return render(request, 'homepage/register.html')

def updateinfo(request):
    if request.method == 'POST':
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        userobject = request.POST.get('objectchoice')
        grade = request.POST.get('gradelevelchoice')
        yearofbirth = request.POST.get('yearofbirth')
        guardian = request.POST.get('guardian')
        email = request.POST.get('email')
        phone = request.POST.get('phone')

        print(userobject, grade)
        
        current_user = request.user
        account = Account.objects.get(username = current_user.id)

        new_user_detail = UserDetail()
        new_user_detail.accountid = account
        new_user_detail.lastname = lastname
        new_user_detail.firstname = firstname
        new_user_detail.objectchoice = userobject
        new_user_detail.gradelevel = grade
        new_user_detail.yearofbirth = yearofbirth
        new_user_detail.guardian = guardian
        new_user_detail.email = email
        new_user_detail.phone = phone
        new_user_detail.save()
    
        # print(new_account.avatar)
        return redirect('homepage:index')
    # return render(request, 'homepage/updateinfo.html')
    return render(request, 'homepage/profile.html')

def mylogin(request):
    if request.user.is_authenticated: 
        # print(request.get_full_path)
        # lay id trang hien tai va quay lai sau khi dang nhap -> how
        # return redirect(request.path)
        enurl = 'homepage:index'

        return redirect('homepage:index')
    else:
        if request.method == 'POST':
            # Lấy username và password
            username = request.POST.get('username')
            password = request.POST.get('password')  
            # kiểm tra xem username và password có trong dữ liệu không
            user = authenticate(username=username, password=password)
            if user is not None: # Nếu tìm thấy user có username và password đã nhập
                if user.is_active: # Tài khoản có bị vô hiệu chưa - đã/ còn hiệu lực
                    print('active')
                    login(request, user)
                    # trả về trang index
                    enurl = 'homepage:index'
                    # current_path = request.path
                    # url = {
                    #     '/gioi-thieu': 'homepage:about',
                    #     '/danh-sach-bai-hoc': 'homepage:lesson',
                    #     '/luyen-tap': 'homepage:practice',
                    #     '/kiem-tra': 'homepage:test',
                    #     '/cuoc-thi': 'homepage:competition',
                    #     '/tin-tuc': 'homepage:news',
                    #     '/tai-lieu': 'homepage:document',
                    #     '/ho-tro': 'homepage:support',
                    #     '/cau-hoi-thuong-gap': 'homepage:faq',
                    #     '/lien-he': 'homepage:contact',
                    # }
                    # if current_path in url.keys():
                    #     enurl = url[current_path]
                    # print(current_path)
                    
                    return redirect(enurl)
                else:
                    return render(request, 'homepage/login.html', {'message':'Tài khoản đã bị vô hiệu hóa'})
            else:
                return render(request, 'homepage/login.html', {'message':'Tài khoản không tồn tại'})
        return render(request, 'homepage/login.html')
    
def mylogout(request):
    # Nếu không có tài khoản nào thì không thực hiện hàm đăng xuất
    try:
        logout(request)
    except:
        pass
    # Nếu đăng xuất thành công => trả về trang đăng nhập - login
    # return render(request, 'homepage/login.html')
    enurl = 'homepage:index'
    # current_path = next_path
    # print(current_path)
    url = {
        '/gioi-thieu': 'homepage:about',
        '/danh-sach-bai-hoc': 'homepage:lesson',
        '/luyen-tap': 'homepage:practice',
        '/kiem-tra': 'homepage:test',
        '/cuoc-thi': 'homepage:competition',
        '/tin-tuc': 'homepage:news',
        '/tai-lieu': 'homepage:document',
        '/ho-tro': 'homepage:support',
        '/cau-hoi-thuong-gap': 'homepage:faq',
        '/lien-he': 'homepage:contact',
    }
    # if current_path in url.keys():
    #     enurl = url[current_path]
    # print(current_path)
    
    return redirect(enurl)
    # return redirect('homepage:index')

def resetpassword(request):
    # send_mail(
    #     'Subject here',
    #     'Here is the message.',
    #     'tuyethuynh2k31@gmail.com',
    #     ['tuyethuynh3036@gmail.com'],
    #     fail_silently=False,
    # )
    return render(request, 'homepage/resetpassword.html')

def dashboard(request, id):
    user = User.objects.get(pk = id)
    account = Account.objects.get(username = id)
    userdetail = UserDetail.objects.get(accountid = account.pk)
    
    if request.method == 'POST': 
        avatar = request.FILES.get('avatar')
        
        account.avatar = tokenFile(avatar,'media/users', user.username ,1)
        account.save()

    context = {
        'user': user,
        'account': account,
        'userdetail': userdetail,
    }
    return render(request, 'homepage/dashboard.html', context)

# lessons
def lesson(request):
    topiclessons = {}
    for i in TopicLesson.objects.all():
        topiclessons[i] = Lesson.objects.filter(topiclessonid=i)
    context = {
        'topiclessons': topiclessons,
    }

    # dang nhap -> ktra tracking theo user, lesson -> dung filter trackingactivity

    if request.user.is_authenticated: 
        current_user = request.user
        account = Account.objects.get(username = current_user.id)

        # tracking theo lesson -> thanh tien do lesson hoac mo khoa lesson on tap trong chu de do
        # tracking theo chu de -> mo khoa chu de tiep theo

        for topic in topiclessons:
            # for lesson in lessons:
            for lesson in topiclessons[topic]: 
                activities = Activity.objects.filter(lessonid = lesson)
                tracking = TrackingActivity.objects.filter(accountid = account, lessonid = lesson)
                if len(tracking) != 0:
                    lesson.percent = len(tracking)/len(activities)*100
                else:
                    lesson.percent = 0
    else:
        for topic in topiclessons:
            for lesson in topiclessons[topic]: 
                lesson.percent = 0

    return render(request, 'homepage/lesson.html', context)

def lessondetail(request, id1, id2):
    topiclesson = TopicLesson.objects.get(pk=id1)
    lesson = Lesson.objects.get(pk=id2)
    activities = Activity.objects.filter(lessonid=id2).order_by('activityorder')
    
    if request.user.is_authenticated: 
        current_user = request.user
        account = Account.objects.get(username = current_user.id)
        
        # tracking
        tracking = TrackingActivity.objects.filter(accountid = account, lessonid = lesson)
        if len(tracking) != 0:
            lesson.percent = len(tracking)/len(activities)*100
        else:
            lesson.percent = 0
    else:
        lesson.percent = 0

    context = {
        'topiclesson': topiclesson,
        'lesson': lesson,
        'activities': activities,
    }
    return render(request, 'homepage/lessondetail.html', context)

def activitydetail(request, id1, id2, id3):
    topiclesson = TopicLesson.objects.get(pk=id1)
    lesson = Lesson.objects.get(pk=id2)    
    activity = Activity.objects.get(activityid=id3)
    context = {
        'topiclesson': topiclesson,
        'lesson': lesson,

homepage/templates/homepage/activitydetail.html
{% extends "homepage/base2.html" %}

{% load static %}

{% block content %}

<!-- <div class="content-wrapper"> -->
<div>

    <!-- <div class="breadcrumb-wrap bg-f br-bg-4">
        <div class="overlay op-8 bg-white"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-8 offset-xl-2 col-lg-10 offset-lg-1 col-md-10 offset-md-1">
                    <div class="breadcrumb-title">
                        <h2>Vui học cùng Ong Vàng</h2>
                        <ul class="breadcrumb-menu list-style">
                            <li><a href="{% url 'homepage:index' %}">Trang chủ </a></li>
                            <li>Bài học</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

    <!-- <section class="course-wrap ptb-100"> -->
    <section class="pt-2 pb-5">
        <div class="container pt-3">
            {% csrf_token %}
            <div id="gamediv" class="d-flex justify-content-center">
                <a href="#">
                    <button class="btn style1 d-block">HƯỚNG DẪN</button> 
                    <!-- SHOW VIDEO HƯỚNG DẪN -->
                </a>
                <iframe id="iframegame"
                    style="width: 1200px; height:700px; overflow: hidden;border-radius: 10px;padding: 1px;background: rgb(80, 78, 69)"
                    src={{activity.link}} scrolling="no">
                </iframe>
                <a href="{% url 'homepage:lessondetail' topiclesson.pk lesson.pk %}">
                    <button class="btn style1 d-block">QUAY LẠI</button> 
                </a>
            </div>

            <script>
                var topiclessonid = "{{topiclesson.pk}}"
                var lessonid = "{{lesson.pk}}"
                var activityid = "{{activity.pk}}"
                console.log(activityid)
                function sendtobackend() {
                    $.ajax({
                        url: "/ajaxtrackcompleteactivity",
                        data: {
                            'topiclessonid': topiclessonid,
                            'lessonid': lessonid,
                            'activityid': activityid,
                        },
                        dataType: 'json',
                        success: function (data) {
                            if (data.flag) {
                                console.log('json')
                                clearInterval(loops)
                                // $('#thacmac').html("Hỏi Đáp")
                                // $('#thacmaccontent').html("Em Vừa Hoàn Thành Trò Chơi Này Kết Quả Đã Được Lưu Lại")
                                // wingame();
                            }
                        }
                    })
                }
                // function wingame(){
                //                     $.magnificPopup.open({
                //                     items: {
                //                     src: '#winpop'
                //                         },
                //                     closeBtnInside: true,
                //                     type: 'inline'
                //                     });
                //                 }

                $(document).ready(function () {
                    setTimeout(function () {
                        loops = setInterval(function () {
                            var check = document.getElementById("iframegame").contentWindow.blazewarriorsstatusgame;
                            console.log(check)

                            if (check == true) {
                                clearInterval(loops)

                                setTimeout(function () {
                                    sendtobackend();
                                }, 1000)
                            }
                        }, 500);

                    }, 1000)
                })
            </script>
        </div>
    </section>
</div>

{% endblock %}

homepage/templates/homepage/lesson.html
{% extends "homepage/base.html" %}

{% load static %}

{% block content %}

<div class="content-wrapper lesson">

    <div class="breadcrumb-wrap bg-f br-bg-4">
        <div class="overlay op-8 bg-white"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-8 offset-xl-2 col-lg-10 offset-lg-1 col-md-10 offset-md-1">
                    <div class="breadcrumb-title">
                        <h2>Vui học cùng Ong Vàng</h2>
                        <ul class="breadcrumb-menu list-style">
                            <li><a href="{% url 'homepage:index' %}">Trang chủ </a></li>
                            <li>Bài học</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="course-wrap ptb-100">
        <div class="container">
            {% csrf_token %}
            {% for topic, lessons in topiclessons.items %} 
            <h2 class="text-danger"><i class="far fa-keyboard"></i>&ensp;{{topic}}</h2>
            <div class="row">
                {% for lesson in lessons %}
                <div class="col-xl-3 col-lg-6 col-md-6">
                    <div class="course-card style3">
                        <div class="course-img">
                            {% if user.is_authenticated %}
                            <a href="{% url 'homepage:lessondetail' topic.pk lesson.pk %}">
                                <img src="/{{lesson.image}}" alt="Image">
                            </a>
                            {% else %}
                                {% if lesson.lessonorder <= 3 %}
                                <a href="{% url 'homepage:lessondetail' topic.pk lesson.pk %}">
                                    <img src="/{{lesson.image}}" alt="Image">
                                </a>
                                {% else %}
                                <img src="/media/lessons/images/lock.png" alt="Image">
                                {% endif %}
                            {% endif %}
                        </div>
                        <!-- <div class="skills style1">
                            <div class="skillbar clearfix" data-percent="89%">
                                <div class="skillbar-bar" style="width: {{lesson.percent}}%">
                                </div>
                            </div>
                        </div> -->
                        <div class="course-info">
                            <h3 class="course-title">
                                <a  {% if user.is_authenticated %} href="{% url 'homepage:lessondetail' topic.pk lesson.pk %}" {% endif %}>
                                    {{lesson.description}}
                                </a>
                            </h3>
                            <div class="course-rating-wrap">
                                <div class="course-category">
                                    <a href="{% url 'homepage:lessondetail' topic.pk lesson.pk %}">
                                        {{lesson.name}}
                                    </a>
                                </div>
                                
                                <ul class="ratings list-style">
                                    {# with ''|center:lesson.stars as range #}
                                    {# for _ in range #}
                                    <!-- {{ forloop.counter }} -->
                                    <!-- <li><i class="las la-star"></i></li> -->
                                    {# endfor #}
                                    {# endwith #}
                                </ul>
                            </div>
                            

                            <div class="row">
                                <div class="col-3">
                                    {{lesson.percent}}%
                                </div>
                                <div class="col-2">
                                    <div class="skills style1" style="width: 500%; padding: auto">
                                        <div class="skillbar clearfix" data-percent="89%">
                                            <div class="skillbar-bar" style="width: {{lesson.percent}}%">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- <div class="course-metainfo">
                                <div class="course-Lectures">
                                    <a href="course-details.html">20 Lectures</a>
                                </div>
                                <div class="course-enroll">
                                    <a href="register.html" class="btn">Enroll Now</a>
                                </div>
                            </div> -->
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endfor %}
            <!-- <div class="page-navigation">
                <div class="row">
                    <div class="col-lg-12 ">
                        <ul class="page-nav list-style">
                            <li><a href="#"> <i class="flaticon-left-arrow"></i> </a></li>
                            <li><a class="active" href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#"> <i class="flaticon-next"></i> </a></li>
                        </ul>
                    </div>
                </div>
            </div> -->
        </div>
    </section>

</div>

{% endblock %}

homepage/templates/homepage/login.html
{% extends "homepage/base2.html" %}

{% load static %}

{% block content %}

<!-- <div class="content-wrapper"> -->

    <!-- <div class="breadcrumb-wrap bg-f br-bg-1">
        <div class="overlay op-8 bg-white"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-8 offset-xl-2 col-lg-10 offset-lg-1 col-md-10 offset-md-1">
                    <div class="breadcrumb-title">
                        <h2>ĐĂNG NHẬP</h2>
                        <ul class="breadcrumb-menu list-style">
                            <li><a href="index.html">TRANG CHỦ </a></li>
                            <li>ĐĂNG NHẬP</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

    <section class="Login-wrap pt-100 pb-100 bg-login-register">
        <div class="container">
            <div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2 col-md-8 offset-md-2">
                <form class="login-form" method="POST">
                    {% csrf_token %}
                    <div class="login-header bg-green">
                        <h2 class="text-center mb-0">ĐĂNG NHẬP</h2>
                    </div>
                    <div class="login-body">
                        <form class="form-wrap" action="#">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="username">Tên đăng nhập *</label>
                                        <input id="username" name="username" type="text" placeholder="Tên đăng nhập/Email/Số điện thoại"
                                            required>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="password">Mật Khẩu *</label>
                                        <input id="password" name="password" type="password" placeholder="Nhập mật khẩu">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-6">
                                    <div class="form_group mb-20">
                                        <input type="checkbox" id="test_1">
                                        <label for="test_1">Ghi Nhớ</label>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-6 text-end mb-20">
                                    <a href="forgot-pwd.html" class="link style3">Quên Mật Khẩu?</a>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <button class="btn style7 w-100 d-block">Đăng Nhập</button>
                                    </div>
                                </div>
                                <div class="col-md-12 text-center">
                                    <p class="mb-0">Chưa có tài khoản? <a class="link style3" href="{% url 'homepage:register' %}">Đăng ký ngay nào!</a></p>
                                </div>
                            </div>
                        </form>
                    </div>
                </form>
            </div>
        </div>
    </section>

<!-- </div> -->

{% endblock %}

homepage/templates/homepage/practice.html
{% extends "homepage/base.html" %}

{% load static %}

{% block content %}

<div class="content-wrapper">

    <div class="breadcrumb-wrap bg-f br-bg-4">
        <div class="overlay op-8 bg-white"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-8 offset-xl-2 col-lg-10 offset-lg-1 col-md-10 offset-md-1">
                    <div class="breadcrumb-title">
                        <h2>Truy Tìm Kho Báu</h2>
                        <ul class="breadcrumb-menu list-style">
                            <li><a href="{% url 'homepage:index' %}">Trang chủ </a></li>
                            <li>Luyện Tập</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <section class="course-wrap ptb-100">
        <div class="container">
            {% csrf_token %}
            {% for topic, games in topicpractices.items %} 
            <h2 class="text-center">{{topic}}</h2>            
            <div class="row justify-content-center">
                {% for game in games %}
                <div class="col-xl-5 col-lg-6 col-md-6">
                    <div class="course-card style3">
                        <div class="course-img">
                            {% if user.is_authenticated %}
                            <a href="{% url 'homepage:practicelevel' game.gameid %}">
                                <img src="{{game.image}}" alt="{{game.image}}" style="width:100%">
                            </a>
                            {% else %}
                                {% if game.gameorder is 1 %}
                                <a href="{% url 'homepage:practicelevel' game.gameid %}">
                                    <img src="{{game.image}}" alt="{{game.image}}" style="width:100%">
                                </a>
                                {% else %}
                                <img src="../../../media/practices/images/lock.png" alt="Image">
                                {% endif %}
                            {% endif %}
                            <a href="{% url 'homepage:practicelevel' game.gameid %}">
                                <!-- <img src="{{game.image}}" alt="{{game.image}}" style="width:100%"> -->
                            </a>
                        </div>
                        <div class="course-info">
                            <h3 class="course-title">
                                <a href="#">{{game.description}}</a>
                            </h3>
                            <div class="course-rating-wrap">
                                <div class="course-category">
                                    <a href="{% url 'homepage:practicelevel' game.pk %}">{{game.name}}</a>
                                </div>
                                     
                            </div>
                            <div class="course-rating-wrap">
                                <ul class="ratings list-style">
                                    {% with ''|center:game.stars as range %}
                                    {% for _ in range %}
                                    <!-- {{ forloop.counter }} -->
                                    <li><i class="las la-star"></i></li>
                                    {% endfor %}
                                    {% endwith %}
                                </ul>
                            </div>
                            <!-- <div class="course-metainfo">
                                <div class="course-Lectures">
                                    <a href="course-details.html">20 Lectures</a>
                                </div>
                                <div class="course-enroll">
                                    <a href="register.html" class="btn">Enroll Now</a>
                                </div>
                            </div> -->
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endfor %}
            <!-- <div class="page-navigation">
                <div class="row">
                    <div class="col-lg-12 ">
                        <ul class="page-nav list-style">
                            <li><a href="#"> <i class="flaticon-left-arrow"></i> </a></li>
                            <li><a class="active" href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#"> <i class="flaticon-next"></i> </a></li>
                        </ul>
                    </div>
                </div>
            </div> -->
        </div>
    </section>
</div>
{% endblock %}